name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0' 

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build 

      - name: Install AWS CLI
        run: |
          sudo apt-get install awscli

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://pruebis1 --delete --region us-east-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
